#eureka集群配置
#指服务明端口号
server:
  port: 8082
  #由于需要相互注册,所以就也需要配置注册的相关内容
  #服务映射名称
spring:
  application:
    name: spring-consumer
  cloud:
    stream:
      bindings:
        myInput:
          group: groupB